services:
#    user.example:
#        class: Timiki\Bundle\UsersBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

     users.provider:
         class: Timiki\Bundle\UsersBundle\Security\UsersProvider
         arguments: [%users.provider%, %users.options%, '@service_container']

